name: Build and Push Docker Images

on:
  push:
    paths:
      - hospital-management/**

jobs:
  build-push-appointment-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/appointment-service:latest -f dockerfile .
        working-directory: hospital-management/appointment-service

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/appointment-service:latest
          
  build-push-case-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Build Docker Image for case-service
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/case-service:latest -f dockerfile .
        working-directory: hospital-management/case-service

      - name: Push Docker Image for case-service
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/case-service:latest
          
  build-push-directory-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Build Docker Image for directory-service
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/directory-service:latest -f dockerfile .
        working-directory: hospital-management/directory-service

      - name: Push Docker Image for directory-service
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/directory-service:latest
          
  build-push-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Build Docker Image for api-gateway
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/api-gateway:latest -f dockerfile .
        working-directory: hospital-management/api-gateway

      - name: Push Docker Image for api-gateway
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/api-gateway:latest
          
  build-push-patient-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PAT }}

      - name: Build Docker Image for patient-service
        run: docker build -t ${{ secrets.DOCKER_REGISTRY_USER }}/patient-service:latest -f dockerfile .
        working-directory: hospital-management/patient-service

      - name: Push Docker Image for patient-service
        run: docker push ${{ secrets.DOCKER_REGISTRY_USER }}/patient-service:latest
